### ISSUE TITLE
Helm repo not updated

### ISSUE THREAD

**Issue by DevPre24** [insuusvenerati/helm-charts#1]
@insuusvenerati Just noticed your helm repository `https://insuusvenerati.github.io/helm-charts` is not updated to 0.4.0. Maybe it has to do with the failed CI run. Could you look into it? Thanks!

**Comment by insuusvenerati** [comment]
Oops, forgot to index. My CI isn't running at the moment since it's self hosted. It's incomplete as well since getting `git` to work properly in CI has been a challenge. If you have any suggestions, including using another CI like Github actions, i'm down for anything at this point :) 

Thanks for the report!
